### ISSUE TITLE
Could not locate call adapter for retrofit.Call<okhttp3.ResponseBody>

### ISSUE THREAD

**Issue by reliveyy** [10424102/whisky-android#11]
27392-28361/org.team10424012.whisky E/BlackServerAccount: account activation failed: BlackServerAccount[phone=123456789, auth=null, profile=null, valid=false, visiable=false, usedCount=0]
                                                                             java.lang.IllegalArgumentException: Unable to create call adapter for retrofit.Call<okhttp3.ResponseBody>
                                                                                 for method BlackServerApi.isPhoneAvailable
                                                                                 at retrofit2.Utils.methodError(Utils.java:154)
                                                                                 at retrofit2.MethodHandler.createCallAdapter(MethodHandler.java:52)
                                                                                 at retrofit2.MethodHandler.create(MethodHandler.java:25)
                                                                                 at retrofit2.Retrofit.loadMethodHandler(Retrofit.java:164)
                                                                                 at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
                                                                                 at java.lang.reflect.Proxy.invoke(Proxy.java:397)
                                                                                 at $Proxy3.isPhoneAvailable(Unknown Source)
                                                                                 at org.team10424102.whisky.components.auth.BlackServerAccount.activate(BlackServerAccount.java:64)
                                                                                 at org.team10424102.whisky.controllers.WelcomeActivity$PhoneValidationTask.doInBackground(WelcomeActivity.java:100)
                                                                                 at org.team10424102.whisky.controllers.WelcomeActivity$PhoneValidationTask.doInBackground(WelcomeActivity.java:76)
                                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                 at java.lang.Thread.run(Thread.java:818)
                                                                              Caused by: java.lang.IllegalArgumentException: Could not locate call adapter for retrofit.Call<okhttp3.ResponseBody>. Tried:
                                                                              \* retrofit2.ExecutorCallAdapterFactory
                                                                                 at retrofit2.Retrofit.nextCallAdapter(Retrofit.java:228)
                                                                                 at retrofit2.Retrofit.callAdapter(Retrofit.java:194)
                                                                                 at retrofit2.MethodHandler.createCallAdapter(MethodHandler.java:50)
                                                                                    ... 14 more

按照 [retrofit-2.0.0-beta3 的文档](https://github.com/square/retrofit/blob/master/CHANGELOG.md)上面的指示，使用 ResponseBody 代替 Response 依然出现上面的错误

**Comment by reliveyy** [comment]
是 retrofit2 的包名问题
